#!/bin/sh
#
# $FML: list_up_message_arg,v 1.1 2003/05/31 04:42:31 fukachan Exp $
#

dir=../../fml/share/message/

grep -r _arg_ $dir |\
perl -nle 's/_arg_\w+/print $&/e'|\
sort|\
uniq -c|\
sort -n

exit 0
