#
# $FML: Makefile.local,v 1.2 2002/03/21 07:09:30 fukachan Exp $
#

FORMATER = ../../../utils/bin/varlist.pl
SOURCE   =  ../../../etc/default_config.cf.ja.in

VARLIST  = internals/list.variables.sgml

$(VARLIST): $(SOURCE)
	$(FORMATER) -sgml $(SOURCE) > $(VARLIST).new
	mv $(VARLIST).new $(VARLIST)

install: install_image

install_image: ../../en/figures/command.dataflow.gif

../../en/figures/command.dataflow.gif: command/states.gif
	cp command/states.gif ../../en/figures/command.dataflow.gif
