#
# $FML: Makefile,v 1.5 2008/08/23 00:38:20 fukachan Exp $
#

all: doc

doc:
	(cd tutorial ; make )
	(cd tech ; make )
	(cd todo ; make )

clean:
	(cd tutorial ; make clean )
	(cd tech ; make clean )
	(cd todo ; make clean )

