#
# $FML: Makefile,v 1.3 2002/04/01 13:06:58 fukachan Exp $
#

all: doc

doc:
	(cd tutorial ; make )
	(cd tech ; make )
	(cd todo ; make )
	(cd faq ; make )
	(cd recipes ; make )

clean:
	(cd tutorial ; make clean )
	(cd tech ; make clean )
	(cd todo ; make clean )
	(cd faq ; make clean )
	(cd recipes ; make clean )
