#
# $FML: Makefile,v 1.1 2001/04/28 10:02:19 fukachan Exp $
#

all: doc

doc:
	(cd tutorial ; make )
	(cd tech ; make )
	(cd todo ; make )
	(cd faq ; make )

clean:
	(cd tutorial ; make clean )
	(cd tech ; make clean )
	(cd todo ; make clean )
	(cd faq ; make clean )
